### ISSUE TITLE
添加广期所支持

### ISSUE THREAD

**Issue by vnpy** [vnpy/vnpy_uft#12]
更新API版本，增加GFEX支持【F6】

**Comment by noranhe** [comment]
论坛原帖链接https://www.vnpy.com/forum/topic/31508-veighna-traderzai-windowsan-zhuang-uftjie-kou-qi-dong-zheng-chang-dan-chu-xian-keyerror:-f6?page=1#pid58976

**Comment by vnpy** [comment]
已修复
