### ISSUE TITLE
vnpy_uft is using uft api of version 3.7.1.16 instead of 3.7.2.4, please update

### ISSUE THREAD

**Issue by fundproject** [vnpy/vnpy_uft#4]
您好，使用vnpy_uft接口进行市价单交易返回输入参数错误。经排查发现vnpy_uft实际上编译的uft版本为：3.7.1.16 而非文档中所写的 3.7.2.4 ， 用此版本请求券商的服务器则会出现参数错误的问题。具体错误参数为：OrderCommand ，旧版本（vnpy实际支持的版本）这个参数是str， 而新版本中已经更新为int。 请开发人员及时更正vnpy_uft接口。 谢谢。

可参考以下文件中列出的版本号：https://github.com/vnpy/vnpy_uft/blob/main/vnpy_uft/api/include/uft/HSDataType.h
![image](https://user-images.githubusercontent.com/89562711/131270766-1d96feb8-fb83-40bb-8645-f5822d1621ff.png)

**Comment by Edanflame** [comment]
感谢反馈，已在https://github.com/vnpy/vnpy_uft/pull/5 中修复
